In [27]:
import numpy as np
import pandas as pd
import os


In [ ]:
obesity_data = pd.read_csv("/Users/vivekkumar/Desktop/project/obesity_final.csv")

print(obesity_data.head(10))


   Age  Gender Alcohol_consumption High_calories_foodconsumption_frequency  \
0   21  Female                  no                                      no   
1   21  Female           Sometimes                                      no   
2   23    Male          Frequently                                      no   
3   27    Male          Frequently                                      no   
4   22    Male           Sometimes                                      no   
5   29    Male           Sometimes                                     yes   
6   23  Female           Sometimes                                     yes   
7   22    Male           Sometimes                                      no   
8   24    Male          Frequently                                     yes   
9   22    Male                  no                                     yes   

   Vegetable_consumption_frequency  Avg_no_of_meals  \
0                              2.0              3.0   
1                              

In [4]:
print(obesity_data.columns)

Index(['Age', 'Gender', 'Alcohol_consumption',
       'High_calories_foodconsumption_frequency',
       'Vegetable_consumption_frequency', 'Avg_no_of_meals',
       'Calorie_consumption_monitoring', 'Smoking_habits', 'Water_consumption',
       'Family_history', 'Physical_activity', 'Mobile_screentime',
       'Food_consumed_between_meals', 'Transpotation', 'obesity_level',
       'Bmi_index'],
      dtype='object')


Can smoking and alcohol habits predict whether someone is likely to be obese? 

In [ ]:
%pip install scikit-learn


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 5.0 MB/s eta 0:00:00
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 44.6 MB/s eta 0:00:0000:010:01
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.4/22.4 MB 32.4 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score



In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

X = obesity_data[['Smoking_habits', 'Alcohol_consumption']]
X = X.apply(LabelEncoder().fit_transform)

y = obesity_data['obesity_level']
y = LabelEncoder().fit_transform(y)  # Only if it's categorical and you want to force numeric regression


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse:.2f}")
print(f"R² Score: {r2:.2f}")


Mean Squared Error: 3.71
R² Score: 0.01


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
X = obesity_data[['Smoking_habits', 'Alcohol_consumption']]
X = X.apply(LabelEncoder().fit_transform)

y = obesity_data['obesity_level']
y = LabelEncoder().fit_transform(y) 



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

print("Classification Report:") 
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("Accuracy Score:", accuracy_score(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        59
           1       0.00      0.00      0.00        61
           2       0.24      0.47      0.32        70
           3       0.60      0.09      0.16        64
           4       0.23      1.00      0.38        60
           5       0.00      0.00      0.00        55
           6       0.13      0.04      0.06        49

    accuracy                           0.24       418
   macro avg       0.17      0.23      0.13       418
weighted avg       0.18      0.24      0.14       418


Confusion Matrix:
[[ 0  0 27  1 30  0  1]
 [ 0  0 24  2 31  0  4]
 [ 0  0 33  0 33  0  4]
 [ 0  0 12  6 45  0  1]
 [ 0  0  0  0 60  0  0]
 [ 0  0 15  0 37  0  3]
 [ 0  0 25  1 21  0  2]]
Accuracy Score: 0.24162679425837322


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  